
songs = [
    "Danny Boy.md",
    "Handsome Molly.md",
    "Whiskey in the Jar.md",
    "Wild Mountain Thyme.md",
]

notation = "english"

[[output]]
file = "songbook.tex"
template = "pdf.hbs"
font = "DejaVu Sans"
dpi = 144
process = "latexmk -xelatex {{file}}"

[[output]]
file = "songbook.html"
template = "html.hbs"

[[output]]
file = "songbook.hovorka.xml"
format = "hovorka"

[[output]]
file = "songbook.json"

[book]
title = "Bard Songbook"
subtitle = "An example project"
chorus_label = "Ch"
front_img = "guitar.jpg"
title_note = "A set of a few non-copyrighted songs."
