version = 2

songs = [
    "Danny Boy.md",
    "Handsome Molly.md",
    "Whiskey in the Jar.md",
    "Wild Mountain Thyme.md",
]

notation = "english"

[[output]]
file = "songbook.pdf"
dpi = 144

[[output]]
file = "songbook.html"

[[output]]
file = "songbook.hovorka.xml"
format = "hovorka"

[[output]]
file = "songbook.json"

[[output]]
file = "songbook.xml"

[book]
title = "Bard Songbook"
subtitle = "An example project"
chorus_label = "Ch"
front_img = "guitar.jpg"
title_note = "A set of a few non-copyrighted songs."
