language: rust

jobs:
  include:
    - name: Ubuntu Xenial
      os: linux
      dist: xenial
      env: EXE=bard
    - name: MS Windows
      os: windows
      env: EXE=bard.exe

before_install:
  - rustup component add rustfmt clippy

script:
  - cargo fmt -- --check && cargo test --release --locked && cargo clippy

deploy:
  provider: releases
  api_key:
    secure: eziQ5FimTVC6dD7wGbwj9pcsGyqv2Rlrg9cmbGUMpWhmGJlAh83zsMT+nVuKgRH98Hos03jyR11AYNEo/dnsjOHpDqEoAcIVihFL5afVbrtmF++n3p2a8uNVQfLlkss8NpfGilY88JI1iTQEblRTZWcUvV7PGXGxz44NeGdNaot/kTNuN1Lt7Q+oE/OYW10MuOBMA9vm4LmntmuiOkLbxeOeKoZP9E/WUioP72atIHPfTafzMPAHgzsKxh7g/6RrR700NLIPhqlSu4D9/sh1xmhgfFzwqmq64a4D8q07aXFpeqVAqA2hsDP4aRYdQOhSWkuccdq5XPfk+x9bzwTtIeiKL0MDw6HmXYogaG4kXztNZG2P4vPjnqKv6JlfjdLZN/v7ZiTtkRbfSUxikudSgpG7wKx+mT+eYCliTuDg7Y4ZQUWL7TMwHuvAB7HQwaCApvjcj9G4V6ntigSRxsTvvMIUOsr1YPT++UuW9IBp62z/haGYr38gggvMmzFlRjdgU5UGUue1yQlPxqGjok1zBE9wmu93IIQlLT7BFlfo3iG8JKMJcBEwNOf9lcRFURemoUWEU4bAFf+7nuRoHKI8M1FRoF+S12zuPY/G/+cWOmGI1Qw78TAXbsKE2VejgU3+r3POo6h7ov8IIcoljLLqluxMRc+Y0rPk8o6UYUYic7k=
  file: target/release/$EXE
  on:
    repo: vojtechkral/bard
    tags: true
  skip_cleanup: true

cache: cargo
