[package]
name = "bard"
version = "2.0.0-alpha1"
authors = ["Vojtech Kral <vojtech@kral.pm>"]
description = "Creates PDF and HTML songbooks out of easy-to-write Markdown sources."
readme = "README.md"
repository = "https://github.com/vojtechkral/bard"
homepage = "https://github.com/vojtechkral/bard"
license = "Apache-2.0"
keywords = ["music", "markdown"]
edition = "2018"

[lib]
name = "bard"
path = "src/lib.rs"

[[bin]]
name = "bard"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.26"
camino = { version = "1.0.7", features = ["serde1"] }
clap = { version = "4.0.2", features = ["derive"] }
colored = "2.0.0"
comrak = { version = "0.14.0", default_features = false }
ctrlc = "3.1.3"
globset = "0.4.8"
handlebars = "4.3.3"
html5ever = "0.26.0"
image = { version = "0.24.1", default_features = false, features = ["png", "jpeg"] }
lazy_static = "1.4.0"
lexical-sort = "0.3.1"
notify = "5.0"
quick-xml = "0.23.0"
regex = "1.4.5"
semver = "1.0.7"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.39", features = ["preserve_order"] }
thiserror = "1.0.14"
toml = "0.5"
tectonic = "0.9.0"

[dev-dependencies]
assert-json-diff = "2.0.1"
fs_extra = "1.2.0"

[package.metadata.docs.rs]
features = ["docs_rs_pls_dont_build_these_docs_this_is_internal_stuff"]

[package.metadata.deb]
depends = ""

[package.metadata.generate-rpm]
assets = [
    # NB. cargo-generate-rpm auto-updates the target/release path when cross-compiling
    { source = "target/release/bard", dest = "/usr/bin/bard", mode = "755" }
]



[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "01b29f6d8212bc845da64773b18665d682f5ab66"

[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype","harfbuzz[icu,graphite2]"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = ["freetype","harfbuzz[icu,graphite2]"] }
x86_64-unknown-linux-gnu = { install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static", install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }

