[package]
name = "bard"
version = "1.1.0"
authors = ["Vojtech Kral <vojtech@kral.hk>"]
description = "Creates PDF and HTML songbooks out of easy-to-write Markdown sources."
repository = "https://github.com/vojtechkral/bard"
homepage = "https://github.com/vojtechkral/bard"
license = "Apache-2.0"
keywords = ["music", "markdown"]
edition = "2018"

[lib]
name = "bard"
path = "src/lib.rs"

[[bin]]
name = "bard"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.26"
colored = "2.0.0"
comrak = "0.10.0"
ctrlc = "3.1.3"
glob = "0.3"
handlebars = "3.5.3"
image = { version = "0.23.14", default_features = false, features = ["png", "jpeg"] }
lazy_static = "1.4.0"
notify = "4.0.13"
regex = "1.4.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.39"
structopt = "0.3.21"
thiserror = "1.0.14"
toml = "0.5"

[dev-dependencies]
assert-json-diff = "2.0.1"
fs_extra = "1.2.0"
