version = 2

songs = [
    "yippie.md",
]

notation = "english"

[[output]]
file = "songbook.pdf"
sans_font = false

[[output]]
file = "songbook.html"
sans_font = false

[book]
title = "My Songbook"
subtitle = "(You can edit that title!)"
chorus_label = "Ch"
title_note = "(And this note too...)"
