songs = [
    "yippie.md",
]

notation = "english"

[[output]]
file = "songbook.tex"
process = "latexmk -xelatex -interaction=nonstopmode {{file}}"

[[output]]
file = "songbook.html"

[book]
title = "My Songbook"
subtitle = "(You can edit that title!)"
chorus_label = "Ch"
title_note = "(And this note too...)"
