on: [push, pull_request]

name: CI

env:
  MSRV: 1.60.0
  CARGO_DEB: 1.37.0
  CARGO_RPM: 0.8.0
  CARGO_OUTDATED: 0.11.1
  CARGO_AUDIT: 0.17.0
  HANDLEBARS_VER: 4.7.7

jobs:
  fmt:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Perform format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Cache cargo tools
        id: cargo-tools-cache
        uses: actions/cache@v2
        with:
          path: cargo-tools
          key: lint-tools-${{ env.CARGO_OUTDATED }}-${{ env.CARGO_AUDIT }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: lint-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Install cargo tools if not cached
        if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-outdated --version ${{ env.CARGO_OUTDATED }} --root cargo-tools --target-dir cargo-tools-build
          cargo install cargo-audit --version ${{ env.CARGO_AUDIT }} --root cargo-tools --target-dir cargo-tools-build
      - name: Install system dependencies
        run: |
          sudo apt install libgraphite2-dev -y
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Output
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Outdated dependencies
        # TODO: add support for githubActions format in cargo-outdated directly?
        shell: python
        run: |
          import json
          import subprocess
          import os

          env = os.environ.copy()
          env["PATH"] = os.getcwd() + "/cargo-tools/bin:" + env["PATH"]
          ps = subprocess.Popen(['cargo', 'outdated', '--format', 'json'], stdout=subprocess.PIPE, env=env)
          output = json.load(ps.stdout)
          outdated = output['dependencies']

          for dep in outdated:
              msg = "project: {}, compat: {}, latest: {}, kind: {}".format(dep['project'], dep['compat'], dep['latest'], dep['kind'])
              print("::warning title=Outdated dependency '{}'::{}".format(dep['name'], msg))
      - name: Audit
        run: |
          PATH="$PATH:$PWD/cargo-tools/bin" cargo audit

  test-linux:
    name: Test on Linux
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: test-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Install system dependencies
        run: |
          sudo apt install libgraphite2-dev -y
      - name: Test
        run: |
          cargo test --locked
      - name: Install Node.js
        id: apt-packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: nodejs
          version: 1.0
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: test-npm-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Test reference hbs parsing
        run: |
          cargo test --locked -- --ignored --nocapture --exact hbs_js_parse

  test-windows:
    name: Test on Windows
    needs: fmt
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up vcpkg
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
          $env:VCPKG_ROOT=$CARGO_TARGET_DIR
          if([String]::IsNullOrWhiteSpace($env:VCPKG_ROOT)){$env:VCPKG_ROOT="$(pwd)\target"}
          $env:VCPKG_ROOT="$env:VCPKG_ROOT\vcpkg"
          $env:RUSTFLAGS='-Ctarget-feature=+crt-static'
          $env:TECTONIC_DEP_BACKEND="vcpkg"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: test-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Test
        run: |
          $env:VCPKG_ROOT=$CARGO_TARGET_DIR
          if([String]::IsNullOrWhiteSpace($env:VCPKG_ROOT)){$env:VCPKG_ROOT="$(pwd)\target"}
          $env:VCPKG_ROOT="$env:VCPKG_ROOT\vcpkg"
          $env:RUSTFLAGS='-Ctarget-feature=+crt-static'
          $env:TECTONIC_DEP_BACKEND="vcpkg"
          echo $env:VCPKG_ROOT
          ls $env:VCPKG_ROOT
          cargo test --locked

  msrv:
    name: MSRV check
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.MSRV }}
          override: true
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: msrv-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Install system dependencies
        run: |
          sudo apt install libgraphite2-dev -y
      - name: Perform MSRV check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --tests

  build-linux:
    name: Linux build
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci'
    needs:
      - test-linux
      - test-windows
      - msrv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Install APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Cache cargo tools
        id: cargo-tools-cache
        uses: actions/cache@v2
        with:
          path: cargo-tools
          key: build-tools-${{ env.CARGO_DEB }}-${{ env.CARGO_RPM }}
      - name: Install cargo tools if not cached
        if: steps.cargo-tools-cache.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-deb --version ${{ env.CARGO_DEB }} --root cargo-tools --target-dir cargo-tools-build
          cargo install cargo-generate-rpm --version ${{ env.CARGO_RPM }} --root cargo-tools --target-dir cargo-tools-build
      - name: Install system dependencies
        run: |
          sudo apt install libgraphite2-dev -y
      - name: Build
        run: cargo build --locked --release --target=x86_64-unknown-linux-musl
      - name: Generate packages
        run: |
          PATH="$PATH:$PWD/cargo-tools/bin" cargo deb --no-build --target=x86_64-unknown-linux-musl -o target/debian/bard.deb
          PATH="$PATH:$PWD/cargo-tools/bin" cargo generate-rpm --target=x86_64-unknown-linux-musl -o target/generate-rpm/bard.rpm
      # call upload-artifact per file to flatten resulting directory structure
      - name: Upload linux binary
        uses: actions/upload-artifact@v3
        with:
          name: bard-linux
          path: target/x86_64-unknown-linux-musl/release/bard
      - name: Upload deb package
        uses: actions/upload-artifact@v3
        with:
          name: bard-linux
          path: target/debian/bard.deb
      - name: Upload rpm package
        uses: actions/upload-artifact@v3
        with:
          name: bard-linux
          path: target/generate-rpm/bard.rpm

  build-windows:
    name: Windows build
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci'
    needs:
      - test-linux
      - test-windows
      - msrv
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up vcpkg
        run: |
          cargo install cargo-vcpkg
          cargo vcpkg build
          $env:VCPKG_ROOT=$CARGO_TARGET_DIR
          if([String]::IsNullOrWhiteSpace($env:VCPKG_ROOT)){$env:VCPKG_ROOT="$(pwd)\target"}
          $env:VCPKG_ROOT="$env:VCPKG_ROOT\vcpkg"
          $env:RUSTFLAGS='-Ctarget-feature=+crt-static'
          $env:TECTONIC_DEP_BACKEND="vcpkg"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Build
        run: |
          $env:VCPKG_ROOT=$CARGO_TARGET_DIR
          if([String]::IsNullOrWhiteSpace($env:VCPKG_ROOT)){$env:VCPKG_ROOT="$(pwd)\target"}
          $env:VCPKG_ROOT="$env:VCPKG_ROOT\vcpkg"
          $env:RUSTFLAGS='-Ctarget-feature=+crt-static'
          $env:TECTONIC_DEP_BACKEND="vcpkg"
          cargo build --locked --release
      - name: Upload Windows exe
        uses: actions/upload-artifact@v3
        with:
          name: bard-windows
          path: target/release/bard.exe

  daft-release:
    name: Draf Release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-linux
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        # no options -> gets all the artifacts
      - name: Create a Release draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: "bard ${{ github.ref_name }}"
          files: |
            ./bard-linux/bard
            ./bard-linux/bard.deb
            ./bard-linux/bard.rpm
            ./bard-windows/bard.exe
